# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/waffle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),waffle)

$(call add-radio-file-sha1-checked,radio/abl.img,a0b15f50521c13216a67cca882f6214cbf5b2d93)
$(call add-radio-file-sha1-checked,radio/aop.img,c952c324c1185fd46aa986e32067ddc18cc2c6d0)
$(call add-radio-file-sha1-checked,radio/aop_config.img,fc3cccf7a54747a432a38df293e9aebecdaa1c0e)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,9db8b02e89c87ab547cdcb1d45b7c5bf8426dd97)
$(call add-radio-file-sha1-checked,radio/cpucp.img,3e644375844a7978a17f4bd0facae907b8f0b669)
$(call add-radio-file-sha1-checked,radio/cpucp_dtb.img,1090803e00b8a30c06d0c2a5337c0e61f40913ad)
$(call add-radio-file-sha1-checked,radio/devcfg.img,69dcf666d09025ebc57611fb658c0ef27e4dfe59)
$(call add-radio-file-sha1-checked,radio/dsp.img,72075bb397712d2b7753e2a8654cf8e5c2313602)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,18e3ab488062edf3046511411c86f1a19013d8bf)
$(call add-radio-file-sha1-checked,radio/featenabler.img,4bfab680eded171bd6fcbf2c1fbffd5a2b6508e2)
$(call add-radio-file-sha1-checked,radio/hyp.img,74053a3389710a0378618629decde57bf0548800)
$(call add-radio-file-sha1-checked,radio/imagefv.img,e75a1eec5c67adfaf47ec46913be2d87185bf365)
$(call add-radio-file-sha1-checked,radio/keymaster.img,5eea9ce00d6fc93fb503d9ac5e9b3aae6bd1990b)
$(call add-radio-file-sha1-checked,radio/modem.img,c0ab197217c91b3dceca89a313814a2000a5fe90)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,2a0a3bc41fa77874e80515aaee0a151fd7ea2756)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,690ad9bb2494158ad1be64d2837211fa3a65ed63)
$(call add-radio-file-sha1-checked,radio/qupfw.img,316a08951c9a0a2338a54992b729dc793dfb52d5)
$(call add-radio-file-sha1-checked,radio/shrm.img,2d3083e3ada7e733e72adefbd997f23ed919e3a2)
$(call add-radio-file-sha1-checked,radio/splash.img,02a16b8f3e8f9f0214964ad40feadf06690fc526)
$(call add-radio-file-sha1-checked,radio/tz.img,18df4acb0fbdf3ea900ee816d61b4602bde045b0)
$(call add-radio-file-sha1-checked,radio/uefi.img,79c473eb613d0f596f0048874605b3bd9317f361)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,464897063b4369f6823c61f0bf4ce4f7fc63c796)
$(call add-radio-file-sha1-checked,radio/xbl.img,6e69f9182b1a412389ff194c6c4460a04142768a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,4544b5e9e52f79af290fb99f54bb455a634e72d4)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,3bd886b75b23f7aa73847f4b273efc4a0b272943)

endif
